plugins {
    id 'java-library'
    id 'com.ancientmc.acp' version '0.4.0.B+'
}

repositories {
    maven { url = 'https://libraries.minecraft.net' }
    maven { url = 'https://maven.neoforged.net/releases' }
    maven { url = 'https://github.com/ancientmc/ancientmc-maven/raw/maven' }
}

sourceSets {
    main
}

version = '0.0.1' // Your mod version here.

acp {
    data = "com.ancientmc:versions:${minecraft_version}" // Change the version # in gradle.properties. Run the 'supportedVersions' task to see what versions ACP supports.
    loader = 'risugami' // For Alpha 1.2.6, you can change this value to 'risugami' to use Risugami's ModLoader.
    modName = 'mod' // Your mod name here.
}

// Easy access to tasks
tasks.named('decompile')
tasks.named('downloadModLoader') // make sure the version selected has a compatible ModLoader.
tasks.named('runClient')
tasks.named('buildMod')