plugins {
    id 'java-library'
    id 'com.ancientmc.acp' version '0.2.2.+'
    id 'io.github.moist-mason.license-importer' version '1.0'
}

repositories {
    maven { url = 'https://libraries.minecraft.net' }
    maven { url = 'https://maven.neoforged.net/' }
    maven { url = 'https://github.com/ancientmc/ancientmc-maven/raw/maven/' }
}

sourceSets {
    main
}

import com.ancientmc.acp.util.*

version = '0.0.1' // Your mod version here.

licenseimporter {
    url = 'https://raw.githubusercontent.com/ancientmc/license/master/LICENSE'
    output = file(project.projectDir.path + '/LICENSE')
}

acp {
    data = "com.ancientmc.acp:acp-data:${minecraft_version}" // Change the version # in gradle.properties.
    loader = 'risugami'
    modName = 'mod' // Your mod name here.
}

tasks.register('decompile') {
    group = 'decompile'
    dependsOn(':makeVanillaHashes')
}

tasks.register('runClient', JavaExec) {
    group = 'run'
    mainClass = 'acp.client.Start'
    classpath = sourceSets.main.runtimeClasspath
    systemProperty 'java.library.path', Paths.DIR_NATIVES
}

// Older versions of Minecraft run Java 6. You should still set your JDK in your IDE to Java 8.
compileJava {
    options.compilerArgs = ['-g:none', '-source', '1.6', '-target', '1.6']
}

jar { // Intermediate task. Don't share the JAR it generates.
    archiveFileName = 'interm-' + minecraft_version + '.jar'
    exclude ('acp/')
    from(zipTree(file(Paths.EXTRA_JAR))) {
        include('com/')
        include('paulscode/')
    }
}

FileFilter srcFilter = (File file) -> !file.name.startsWith('acp')
FileFilter tempFilter = (File file) -> !file.name.equals(minecraft_version + ".jar") && !file.name.endsWith('.json')
FileFilter runFilter = (File file) -> !file.name.contains('resources') && !file.name.contains('bin')

// WARNING: Running this will delete Minecraft's source code from the source directory. Back up any of your mod code before executing this task!
clean {
    delete(file(Paths.DIR_SRC).listFiles(srcFilter))
    delete(file(Paths.DIR_VANILLA_SRC))
    delete(file(Paths.DIR_VANILLA_RESOURCES))
    if(file(Paths.DIR_RESOURCES).exists()) delete(file(Paths.DIR_RESOURCES).listFiles())
    if(file(Paths.DIR_TEMP).exists()) delete(file(Paths.DIR_TEMP).listFiles(tempFilter))
    if(file(Paths.DIR_RUN).exists()) delete(file(Paths.DIR_RUN).listFiles(runFilter))
}