org.gradle.jvmargs=-Xmx2G
acp_version=0.2.2
minecraft_version=a1.2.6
tool_jarsplitter=net.neoforged.installertools:jarsplitter:3.0.2
tool_mcinjector=de.oceanlabs.mcp:mcinjector:4.1-am
tool_forgeart=net.neoforged:AutoRenamingTool:2.0.8
tool_fernflower=com.ancientmc:fernflower:1.0
tool_diffpatch=net.neoforged:DiffPatch:2.0.14
tool_specialsource=net.md-5:SpecialSource:1.8.3
tool_binpatch=net.neoforged.installertools:binarypatcher:3.0.2